default, server_default and creating new invitation
Maagan-Michael/invitease pull request #44
Opened 2021-12-12 21:32 UTC by KamiTzayig

in order for the default values to be inserted from the db when creating a new sql row you need to add default &server_default to the models.py so sqlalchemy can expect the values to be inserted, also i created the restapi for creating a new order

2021-12-13 09:34 UTC, yarons reviewed
There has been some changes introduced by @inbarbarkai, I want to make sure we're not conflicting, can you please take a look at hist branch and consult him about this?

2021-12-13 16:21 UTC, inbarbarkai commented
Lets merge mine and see, it shouldn't contain too much conflicts if any.

2021-12-13 16:30 UTC, inbarbarkai commented on src/routers/inviter_router.py
> +    new_invitation =  Invitation(
Do some data validations

2021-12-14 18:32 UTC, inbarbarkai requested changes

2021-12-14 18:32 UTC, inbarbarkai commented on src/routers/inviter_router.py
> +    new_invitation =  Invitation(
Why are you using get to create new invite?
Use post or put.
Also, prefably, don't use query parameters for input.
Use the body

2022-01-03 14:57 UTC, yarons commented
@inbarbarkai I'm guessing it's no longer relevant, am I correct?
Sorry @KamiTzayig :(

2022-01-03 15:57 UTC, inbarbarkai commented
@yarons I don't know... That is for @KamiTzayig to decide

2022-01-08 19:11 UTC, yarons commented
@KamiTzayig we should rebase your changes, some of them are required for your UI work.

2022-05-02 11:59 UTC, yarons commented
Conflicting, irrelevant, reopen if necessary.

2022-05-02 11:59 UTC, closed without merging