all_api
Maagan-Michael/invitease pull request #64
Opened 2022-01-09 20:27 UTC by KamiTzayig

api update, includes all api needed for inviter, guard
and added server_defaults on models.py

2022-01-10 05:01 UTC, inbarbarkai requested changes
Align you variable and method names with pep8.

2022-01-10 05:01 UTC, inbarbarkai commented on src/routers/guard_router.py
> +def create_invitations_list():
Isn't it on utilities?

2022-01-10 05:01 UTC, inbarbarkai commented on docker-compose.yml
> +      #  IVT_ENABLE_AUTH: 'true'
Are we sure we want this?

2022-01-10 05:01 UTC, inbarbarkai commented on src/routers/guard_router.py
> +@router.get("/user-name", summary="Gets all the users.")
The name does not not describe the method functionality

2022-01-10 05:01 UTC, inbarbarkai commented on src/routers/inviter_router.py
>  def create_invitations_list():
Duplicate?

2022-01-10 05:01 UTC, inbarbarkai commented on src/routers/inviter_router.py
> +# def update_user(request: UpdateInvitationRequest, invitation_id: str = Path(None, description="The unique identifier of the invitation."), invitation: InvitationRepository = Depends(create_invitati
Remove commented code

2022-01-10 05:06 UTC, inbarbarkai commented on src/routers/guard_router.py
> +def update_user(request: UpdateInviteesRequest,  invitation: InvitationRepository = Depends(create_invitations_list),
The name does not not describe the method functionality

2022-01-10 05:07 UTC, inbarbarkai commented on src/routers/inviter_router.py
> +@router.post("/edit-invitation/{invitation_id}", summary="Updates the invitation information.")
user underscore instead of hyphen

2022-01-10 05:10 UTC, inbarbarkai commented on src/routers/guard_router.py
> +    userList:list(User) = users.query(lambda x: (x.filter(User.user_id.in_( user_id_list))))
The query itself should be implemented in `UserRepository`

2022-01-10 05:10 UTC, inbarbarkai commented on src/routers/guard_router.py
> +    return invitations.query(lambda x: x.filter(or_(Invitation.is_active == True, Invitation.modify_timestamp >=time_limit), Invitation.invitees_arrival_timestamp >= today, Invitation.invitees_arriva
The query itself should be implemented in `InvitationRepository`

2022-01-10 05:10 UTC, inbarbarkai commented on src/routers/inviter_router.py
> +    return invitations.query(lambda x: x.filter(Invitation.user_id == user_id, Invitation.is_active == True, Invitation.invitees_arrival_timestamp >= today))
The query itself should be implemented in `InvitationRepository`

2022-01-13 19:44 UTC, KamiTzayig commented on docker-compose.yml
> +      #  IVT_ENABLE_AUTH: 'true'
for the meantime the http doesn't work with keycloack as we don't have a way to authenticate aside from /docs

2022-01-13 19:55 UTC, KamiTzayig commented on src/routers/inviter_router.py
>  def create_invitations_list():
we need the invitationRepository in guard and inviter, do you have a suggestion for a place to import "create_invitation_list" from?

2022-01-14 06:57 UTC, inbarbarkai commented on src/routers/inviter_router.py
>  def create_invitations_list():
Yes, but I think it exist it utilities

2022-01-14 06:58 UTC, inbarbarkai commented on docker-compose.yml
> +      #  IVT_ENABLE_AUTH: 'true'
Ok

2022-01-14 16:09 UTC, inbarbarkai commented on src/database/invitation_repository.py
> +    def get_invitations_from_constrains(self):
Constraints?

2022-01-14 16:12 UTC, inbarbarkai commented on src/database/invitation_repository.py
> +    def get_invitations_from_constrains(self):
Maybe pending?

2022-01-14 16:37 UTC, KamiTzayig commented on src/database/invitation_repository.py
> +    def get_invitations_from_constrains(self):
updated the function name

2022-01-14 16:37 UTC, KamiTzayig commented on src/database/invitation_repository.py
> +    def get_invitations_from_constrains(self):
get_pending_invitations

2022-01-14 17:46 UTC, inbarbarkai commented on src/routers/inviter_router.py
> +def update_user(request: UpdateInvitationRequest, invitation: InvitationRepository = Depends(create_invitations_list),
Still wrong method name

2022-01-14 18:44 UTC, inbarbarkai commented
Great coding, now just fix all the pep8 violations and we're done

2022-01-14 20:50 UTC, yarons commented
@KamiTzayig @inbarbarkai It can be done as a continuous effort: https://pypi.org/project/pep8/

2022-01-15 05:43 UTC, inbarbarkai commented
@yarons from my experience, code written is not touched unless a fix needs to be introduced.
And even then, only the necessary parts.
Coding conventions are important for code readability.
I don't know a repo that will allow you to add work that doesn't follow it.

2022-01-16 06:56 UTC, yarons commented
@inbarbarkai It's not for current code, it's for future code, think of it more like CI as part of the code, I can also create a GitHub action to check that while creating a PR.

2022-01-16 06:59 UTC, inbarbarkai commented
Fine

2022-01-16 06:59 UTC, inbarbarkai approved these changes

2022-01-16 06:59 UTC, merged